import { Timestamp } from "firebase-admin/firestore";
import { ExtractionConfidence } from "./aiExtraction";

/**
 * Lifecycle states for a proposal as the assignee reviews it.
 *
 * pending   → Created; waiting for the assignee to review.
 * approved  → Assignee accepted the task as-is.
 * rejected  → Assignee dismissed the task.
 * edited    → Assignee modified the title/description before accepting.
 * created   → TaskBot has created the corresponding Google Task.
 */
export type ProposalStatus = "pending" | "approved" | "rejected" | "edited" | "created";

/**
 * Shape of the document stored at proposals/{meetingId}/tasks/{taskId}.
 *
 * The document ID (taskId) matches the ExtractedTask.id generated by the
 * AI extractor. The parent document ID (meetingId) matches the
 * processedTranscripts document ID (which is the Drive file ID).
 */
export interface ProposalDocument {
  // ── Fields carried over from ExtractedTask ──────────────────────────────
  /** Concise, actionable task title. */
  title: string;
  /** Context and explanation drawn from the transcript. */
  description: string;
  /** Email address of the person this task is for. */
  assigneeEmail: string;
  /** Name of the assignee as spoken in the meeting. */
  assigneeName: string;
  /** AI confidence that this is a real committed action item. */
  confidence: ExtractionConfidence;
  /** The ~2–3 verbatim transcript sentences this task came from. */
  transcriptExcerpt: string;
  /** True when the task involves sensitive HR/personal/legal topics. */
  isSensitive: boolean;
  /** ISO 8601 due date if explicitly stated; null otherwise. */
  suggestedDueDate: string | null;
  /** Exact text used to refer to the assignee in the transcript. */
  rawAssigneeText: string;

  // ── Proposal-specific fields ─────────────────────────────────────────────
  /** Document ID of the parent processedTranscripts record (= Drive file ID). */
  meetingId: string;
  /** Firebase Auth UID of the assignee — used for security rules and queries. */
  assigneeUid: string;
  /** Current review state. */
  status: ProposalStatus;
  /** Assignee-modified title (set when status = "edited"). */
  editedTitle?: string;
  /** Assignee-modified description (set when status = "edited"). */
  editedDescription?: string;
  /** When the assignee made their decision. */
  reviewedAt?: Timestamp;
  /** When this proposal document was created. */
  createdAt: Timestamp;
  /** Proposal automatically expires at this time (createdAt + proposalExpiryHours). */
  expiresAt: Timestamp;
  /** Google Tasks task ID, populated after the task is created in Google Tasks. */
  googleTaskId?: string;
}
