// Generated by deploy.sh — do not edit manually.
// Source: deploy/configs/elysianfields-dev.json

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import {
  getFirestore,
  connectFirestoreEmulator,
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";
import {
  getAuth,
  signInWithCustomToken,
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";

const firebaseConfig = {
  apiKey: "AIzaSyAm2vV_6_wLH6NEYLEkqmcNlccmC4BKcnw",
  authDomain: "lithe-bonito-490017-s8.firebaseapp.com",
  projectId: "lithe-bonito-490017-s8",
  storageBucket: "lithe-bonito-490017-s8.firebasestorage.app",
  messagingSenderId: "135321920877",
  appId: "1:135321920877:web:eb0f73da8fb4d0d33ae664",
};

export const projectId = firebaseConfig.projectId;
const firebaseApp = initializeApp(firebaseConfig);
export const db = getFirestore(firebaseApp);
export const auth = getAuth(firebaseApp);
export { signInWithCustomToken };

if (location.hostname === "127.0.0.1" || location.hostname === "localhost") {
  connectFirestoreEmulator(db, "127.0.0.1", 8080);
}
