#!/usr/bin/env bash
# deploy.sh — Deploy TaskBot updates to a specific client project.
# Usage: ./deploy.sh <client-name> [--only functions|hosting|rules|firestore]
# Examples:
#   ./deploy.sh thg
#   ./deploy.sh thg --only functions
#   ./deploy.sh internal --only hosting

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIGS_DIR="$SCRIPT_DIR/configs"

# ── Helpers ───────────────────────────────────────────────────────────────────

bold()  { printf "\033[1m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*"; }
die()   { red "ERROR: $*"; exit 1; }

require_cmd() {
  command -v "$1" &>/dev/null || die "'$1' is required but not installed."
}

# ── Args ──────────────────────────────────────────────────────────────────────

require_cmd firebase
require_cmd jq

[[ $# -ge 1 ]] || die "Usage: $0 <client-name> [--only functions|hosting|rules|firestore]"

CLIENT="$1"
shift

ONLY_FLAG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --only)
      [[ $# -ge 2 ]] || die "--only requires a target (functions, hosting, rules, firestore)"
      ONLY_FLAG="--only $2"
      shift 2
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

CONFIG_FILE="$CONFIGS_DIR/${CLIENT}.json"
[[ -f "$CONFIG_FILE" ]] || die "Config not found: $CONFIG_FILE\nRun ./setup-new-client.sh $CLIENT first."

# ── Load config ───────────────────────────────────────────────────────────────

PROJECT_ID=$(jq -r '.projectId' "$CONFIG_FILE")
REGION=$(jq -r '.region' "$CONFIG_FILE")
GOOGLE_CLIENT_ID=$(jq -r '.google.oauthClientId' "$CONFIG_FILE")
GOOGLE_CLIENT_SECRET=$(jq -r '.google.oauthClientSecret' "$CONFIG_FILE")
KMS_KEY_NAME=$(jq -r '.kms.keyName' "$CONFIG_FILE")
APP_URL=$(jq -r '.appUrl' "$CONFIG_FILE")
# hostingSite overrides the deploy target when the hosting site name differs from projectId
HOSTING_SITE=$(jq -r '.hostingSite // empty' "$CONFIG_FILE")
FIREBASE_API_KEY=$(jq -r '.firebase.apiKey' "$CONFIG_FILE")
FIREBASE_AUTH_DOMAIN=$(jq -r '.firebase.authDomain' "$CONFIG_FILE")
FIREBASE_STORAGE_BUCKET=$(jq -r '.firebase.storageBucket' "$CONFIG_FILE")
FIREBASE_MESSAGING_SENDER_ID=$(jq -r '.firebase.messagingSenderId' "$CONFIG_FILE")
FIREBASE_APP_ID=$(jq -r '.firebase.appId' "$CONFIG_FILE")
ASANA_CLIENT_ID=$(jq -r '.asana.clientId // empty' "$CONFIG_FILE")
ASANA_CLIENT_SECRET=$(jq -r '.asana.clientSecret // empty' "$CONFIG_FILE")

[[ -n "$PROJECT_ID" ]] || die "projectId is empty in $CONFIG_FILE"

# ── Deploy ────────────────────────────────────────────────────────────────────

bold ""
bold "TaskBot — Deploy: $CLIENT"
if [[ -n "$ONLY_FLAG" ]]; then
  bold "  Target: ${ONLY_FLAG#--only }"
fi
bold "  Project: $PROJECT_ID"
bold "  URL: $APP_URL"
echo ""

cd "$REPO_ROOT"

# Switch project
firebase use "$PROJECT_ID" --non-interactive 2>/dev/null || \
  firebase use "$PROJECT_ID"

# Write per-project functions env file (functions/.env.PROJECT_ID)
# Firebase CLI automatically uploads this file during deploy.
# It overrides functions/.env for this specific project.
printf "Writing functions/.env.%s ... " "$PROJECT_ID"
cat > "$REPO_ROOT/functions/.env.${PROJECT_ID}" <<EOF
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
OAUTH_REDIRECT_URI=https://us-central1-${PROJECT_ID}.cloudfunctions.net/oauthCallback
OAUTH_SUCCESS_REDIRECT=${APP_URL}
ASANA_CLIENT_ID=${ASANA_CLIENT_ID}
ASANA_CLIENT_SECRET=${ASANA_CLIENT_SECRET}
ASANA_REDIRECT_URI=${APP_URL}/api/auth/asana/callback
KMS_KEY_NAME=${KMS_KEY_NAME}
EOF
green "done"

# Generate per-project Firebase client config unless deploying functions only
if [[ -z "$ONLY_FLAG" || "$ONLY_FLAG" != "--only functions" ]]; then
  printf "Writing firebase-config.js for %s... " "$PROJECT_ID"
  cat > "$REPO_ROOT/web/js/firebase-config.js" <<EOF
// Generated by deploy.sh — do not edit manually.
// Source: deploy/configs/${CLIENT}.json

import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import {
  getFirestore,
  connectFirestoreEmulator,
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";
import {
  getAuth,
  signInWithCustomToken,
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js";

const firebaseConfig = {
  apiKey: "$FIREBASE_API_KEY",
  authDomain: "$FIREBASE_AUTH_DOMAIN",
  projectId: "$PROJECT_ID",
  storageBucket: "$FIREBASE_STORAGE_BUCKET",
  messagingSenderId: "$FIREBASE_MESSAGING_SENDER_ID",
  appId: "$FIREBASE_APP_ID",
};

export const projectId = firebaseConfig.projectId;
const firebaseApp = initializeApp(firebaseConfig);
export const db = getFirestore(firebaseApp);
export const auth = getAuth(firebaseApp);
export { signInWithCustomToken };

if (location.hostname === "127.0.0.1" || location.hostname === "localhost") {
  connectFirestoreEmulator(db, "127.0.0.1", 8080);
}
EOF
  green "done"
fi

# Build functions unless we're only deploying hosting
if [[ -z "$ONLY_FLAG" || "$ONLY_FLAG" == "--only functions" ]]; then
  printf "Building Cloud Functions... "
  npm --prefix "$REPO_ROOT/functions" run build
  green "done"
fi

# Build the deploy target — use hosting:<site> if a custom site name is set
DEPLOY_TARGET="$ONLY_FLAG"
if [[ -n "$HOSTING_SITE" && ( -z "$ONLY_FLAG" || "$ONLY_FLAG" == "--only hosting" ) ]]; then
  if [[ -z "$ONLY_FLAG" ]]; then
    DEPLOY_TARGET="--only functions,firestore,hosting:${HOSTING_SITE}"
  else
    DEPLOY_TARGET="--only hosting:${HOSTING_SITE}"
  fi
fi

# Deploy
printf "Deploying to %s... " "$PROJECT_ID"
# shellcheck disable=SC2086
firebase deploy $DEPLOY_TARGET --project="$PROJECT_ID" --force

echo ""
green "Deploy complete: $APP_URL"
echo ""
